language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules

install:
  - npm install -g codecov
  - npm install

script:
  - npm run build
  - npm run test:coverage
  - codecov

deploy:
  provider: pages
  local-dir: docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
